language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t wltsankalpa/docker-react-web-app -f Dockerfile.dev .

script:
  - docker run wltsankalpa/docker-react-web-app npm run test -- --coverage
