sudo: required
services:
  - docker

before_install:
  - docker build -t wltsankalpa/docker-react-web-app -f Dockerfile.dev .

script:
  - docker run stephengrider/docker-react npm run test -- --coverage
